# Generated by Django 5.2.13 on 2026-04-11 17:38

import django.contrib.postgres.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_add_import_id_to_card'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='studyset',
            name='study_set_requires_matching_deck_state',
        ),
        migrations.RemoveConstraint(
            model_name='studyset',
            name='study_set_requires_tag_for_tag_kind',
        ),
        migrations.RemoveConstraint(
            model_name='studyset',
            name='study_set_unique_deck',
        ),
        migrations.RemoveConstraint(
            model_name='studyset',
            name='study_set_unique_tag',
        ),
        migrations.RenameIndex(
            model_name='card',
            new_name='core_card_user_id_6eada7_idx',
            old_name='core_card_user__01a54c_idx',
        ),
        migrations.RenameIndex(
            model_name='card',
            new_name='core_card_updated_f1efe2_idx',
            old_name='core_card_updated__ba3f04_idx',
        ),
        migrations.RenameIndex(
            model_name='deck',
            new_name='core_deck_user_id_89ab0e_idx',
            old_name='core_deck_user_parent_idx',
        ),
        migrations.RenameIndex(
            model_name='deck',
            new_name='core_deck_user_id_ad4202_idx',
            old_name='core_deck_user__b72397_idx',
        ),
        migrations.RenameIndex(
            model_name='deck',
            new_name='core_deck_user_id_81fc42_idx',
            old_name='core_deck_user__cd49e9_idx',
        ),
        migrations.RenameIndex(
            model_name='externalid',
            new_name='core_extern_system_8c023e_idx',
            old_name='core_externa_system_71e059_idx',
        ),
        migrations.RenameIndex(
            model_name='import',
            new_name='core_import_user_id_163b71_idx',
            old_name='core_import_user__fca2f7_idx',
        ),
        migrations.RenameIndex(
            model_name='importsession',
            new_name='core_import_user_id_6563b2_idx',
            old_name='core_importsession_user_status_idx',
        ),
        migrations.RenameIndex(
            model_name='importsession',
            new_name='core_import_created_f3dcea_idx',
            old_name='core_importsession_created_idx',
        ),
        migrations.RenameIndex(
            model_name='knowledgenode',
            new_name='core_knowle_knowled_1d762a_idx',
            old_name='core_knowle_knowledg_831e76_idx',
        ),
        migrations.RenameIndex(
            model_name='knowledgenode',
            new_name='core_knowle_knowled_163137_idx',
            old_name='core_knowle_knowledg_eb5e57_idx',
        ),
        migrations.RenameIndex(
            model_name='review',
            new_name='core_review_user_id_0a6f5c_idx',
            old_name='core_review_user__1ba91a_idx',
        ),
        migrations.RenameIndex(
            model_name='review',
            new_name='core_review_card_id_f6fd62_idx',
            old_name='core_review_card_r_3ab683_idx',
        ),
        migrations.AddField(
            model_name='studyset',
            name='decks',
            field=models.ManyToManyField(blank=True, related_name='custom_study_sets', to='core.deck'),
        ),
        migrations.AddField(
            model_name='studyset',
            name='filenames',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, default=list, size=None),
        ),
        migrations.AddField(
            model_name='studyset',
            name='tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, default=list, size=None),
        ),
        migrations.AlterField(
            model_name='cardimportformat',
            name='options',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='cardtype',
            name='field_schema',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='knowledgemap',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='knowledgenode',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='studyset',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='studyset',
            name='kind',
            field=models.CharField(choices=[('deck', 'Deck'), ('tag', 'Tag'), ('custom', 'Custom')], max_length=20),
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AddConstraint(
            model_name='studyset',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('deck__isnull', False), ('kind', 'deck'), ('tag', '')), models.Q(('deck__isnull', True), ('kind', 'tag'), ('tag__gt', '')), models.Q(('deck__isnull', True), ('kind', 'custom'), ('tag', '')), _connector='OR'), name='study_set_kind_constraints'),
        ),
    ]